### ISSUE TITLE
Sparkle Launcher

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/Sparkle#17]
This issue breaks out point 1 from #16 into its own issue.
The Sparkle Launcher should have these properties:

- [x] Is a single smallish window
- [x] Can be opened through Pharo's World menu
- [x] Allow specification of login parameters (more on that below)
- [x] Provide login/logout
- [x] Upon login, open a default explorer window
- [x] Can open additional default explorer windows if logged in
Only one session at a time will be needed for now.

What is needed for session parameters will change as we develop more options for security. Options initially needed:
- [x] Local-image connection (for debugging)
- [x] Host and port of socket connection

**Comment by ericwinger** [comment]
Pull request submitted for integration into development. 

A menu option should appear in the Tools menu called `Sparkle Launcher`
Only single connection supported currently. 
`SpkLauncherPresenter class>>connection` is the access point to the connection once established.
`SparkleLauncher` is the application class.
Closing the launcher closes all explorers as well as the connection. 
Last Host / port entered retained for convenience
