### ISSUE TITLE
Announcement Extensions should move to new homes

### ISSUE THREAD

**Issue by rjsargent** [GemTalk/Sparkle#20]
This is a follow up to Issue #1 (Port Announcements).
There are a number of things in Announcements-Extensions-GemStone that probably deserve a different home.

Behavior.extension.st:Behavior >> includesBehavior: aBehavior [

Collection.extension.st:Collection >> removeAllSuchThat: aBlock [
	This is a correct, but not optimal, default implementation. Other subclasses should have more specific variants.

ExecBlock.extension.st:ExecBlock >> hasReceiver [
ExecBlock.extension.st:ExecBlock >> receiver [

Object.extension.st:Object >> deprecated: aString transformWith: aRule [
	This just redirects to #deprecated:, but offers the potential for more once we have RB tools available.
Object.extension.st:Object >> initialize [

TestAsserter.extension.st:TestAsserter >> should: aBlock notTakeMoreThan: aDuration [
	This is a hack implementation. It doesn't terminate the block when the time expires; it let's the block complete.
	It reports whether the block took too long after it finishes.

**Comment by martinmcclure** [comment]
Collection>>removeAllSuchThat: and Object>>initialize have been added to the base, and Announcements is its own project now, so closing this issue.
