### ISSUE TITLE
Sparkle project maintenance

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Sparkle#21]
- [x] In the Sparkle repository, the `Sparkle/rowan/specs/Sparkle.ston` file specifies the revision as `master` but there is no master branch. Trying to load the project through the Jadeite tools gets a walkback. 

- [ ] Also, it would be handy if loading the Sparkle project automatically loaded the RSR project since it's dependent upon RSR. 

Here is my modified load spec using the `development` branch. This did load into a GemStone server using the Jadeite tools. 
```
RwLoadSpecificationV2 {
        #specName : 'Sparkle',
        #projectName : 'Sparkle',
        #gitUrl : 'git@git.gemtalksystems.com:sparkle',
        #revision : 'development',
        #projectSpecFile : 'rowan/project.ston',
        #componentNames : [
                'Sparkle'
        ],
        #customConditionalAttributes : [
                'tests'
        ],
        #comment : 'Sparkle development load spec'
}
~    
```

**Comment by martinmcclure** [comment]
I think this is sufficiently fixed. If there are still issues in this area, please re-open.
