### ISSUE TITLE
Convenience script to do repeated listens, separated by aborts

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/Sparkle#48]
The current Sparkle/src-gs-server.sh script only does a single listen for connection, then logs out and exits.
It would be convenient to have a script that looped until interrupted. After each disconnection it would abort and listen again.

**Comment by dalehenrich** [comment]
[see the code I've been using to do just that](https://github.com/GemTalk/Sparkle/blob/daleDebugger/src/Sparkle-Scaffolding-GemStone/SpkScaffoldingServiceServer.class.st#L17-L46) ...

**Comment by martinmcclure** [comment]
Fixed in martinDebuggerDev branch, not yet merged to Development

**Comment by martinmcclure** [comment]
This is now merged to development.
