### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/Sparkle#56]
Following the integration of #51, the installation instructions need to be updated.
* You no longer need to have a Git clone of RSR for a server install, just a Sparkle clone.

For newer Pharo.
* The build number of Pharo should be updated in the doc, to 1134. 
*  The Metacello menu in the Repositories window is now (temporarily?) missing. You now have to right-click on "BaselineOfSparkle" in the packages list to find that menu.

**Comment by LisaAlmarode** [comment]
Update .pdf and add to documentation, see 0bdc5402adce7feb2df94c3fa02f4d263515dc58
