### ISSUE TITLE
Loading old connection profile into updated image gives walkback

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Sparkle#61]
I'm not sure what the solution going forward is but saved connection profile files may not be loadable into later versions of the product. The scenario is this - 
1. Save a set of connection profiles to a file -  profiles.ston.
2. In another image, get a more recent version of Sparkle and/or RSR code (or eventually a more recent Sparkle release) 
3. Try to load the profile.ston file into the new image - get an error .

Hopefully, this won't happen often once development of Sparkle is stabilized but we should be aware that if we change the structure of Sparkle connection profile or it's underlying objects, we may see problems like this attached stack. 

We may just say old connection profiles are not loadable into more recent versions. 

[rsrProfileLoadBug.txt](https://github.com/GemTalk/Sparkle/files/6151569/rsrProfileLoadBug.txt)

**Comment by dalehenrich** [comment]
There are ways to fiddle with the STON loading to compensate for different class shapes and even different class names ... so in the long run  there are solutions available with a little bit of extra work ...

**Comment by dalehenrich** [comment]
Apparently the prefs format was changed to be incompatible with the old pref file ...
