### ISSUE TITLE
Send GsProcess>>_isTerminated before performing a debugger action

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Sparkle#63]
Working on some new debugger code, doing a stepOver, got the attached error.  In the GsProcess, the `arStack` variable was nil. Allen tracked it to primitive 719 which does have some logic for nil'ing that inst var if the process has been terminated. 

The likely scenario was the somehow the process had been terminated before the stepOver took place. A recommendation is to do send _isTerminated to the process before any debugger action takes place that would continue the execution. 

Need to discuss with @dalehenrich at some point. 

[20210324 Stack not convertable error.txt](https://github.com/GemTalk/Sparkle/files/6199639/20210324.Stack.not.convertable.error.txt)

**Comment by martinmcclure** [comment]
This is fixed in the tools layer, and a process terminating unexpectedly from under the debugger will result in a process terminated pane.

**Comment by martinmcclure** [comment]
Through quite a few server and Sparkle tools changes to termination, I think this is no longer a problem. Please reopen or re-file if the problem persists.
