### ISSUE TITLE
Launcher: "Set path" wipes out other information

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/Sparkle#67]
Entering the parameters for a GCI connection, I fill out all of the information and get down to "Client Libraries Path." I use the Set Path button, select a library, and it fills out the client libraries path but wipes out all my other information.

**Comment by ericwinger** [comment]
Fixes issue #67. https://github.com/GemTalk/Sparkle/commit/a320134c343362bd09ef2338af236b74a8af22cf After pressing Set Path, all connection gui information was being updated from the working connection profile which had incomplete information. Should only update the path input field on the gui after pressing Set Path.
