### ISSUE TITLE
GCI connections are being set up on a fixed port

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/Sparkle#68]
Once a GCI connection is made, the gem should listen on a wildcard port for an RSR connection, then GCI should return the port number and token to the GCI client so that Pharo can make the RSR connection.

This may be waiting on [RSR #94](https://github.com/GemTalk/RemoteServiceReplication/issues/94), but there is also some launcher work required.

**Comment by kurtkilpela** [comment]
This has been resolved in https://github.com/GemTalk/Sparkle/pull/71

**Comment by kurtkilpela** [comment]
This is resolved in PR #72
