### ISSUE TITLE
Direct Connection broken

### ISSUE THREAD

**Issue by kurtkilpela** [GemTalk/Sparkle#73]
The changes for #68 result in the breaking of Direct Connections. RsrAcceptConnection and RsrInitiateConnection were updated to use a random token. Previously both sized used the null token. The GCI handles this by passing the token back through a GCI call. 

This can be fixed in several ways.

1. Update RsrAcceptConnection and RsrIntiateConnection to allow but no require a token.
2. Add an alternative connection class for use with direct connections
3. Add a means of providing the token when initiating a direct connection

**Comment by martinmcclure** [comment]
I think the best short-term alternative is number 2. 
Number 1 opens a security hole, I think -- someone could connect without a token after setting up a connection that wants to be more secure.
Number 3 is too awkward, at least for now. It leaves token handling as a somewhat manual task.
So using a different connection class, or perhaps a different option given to the existing connection class, seems best.

**Comment by kurtkilpela** [comment]
Fixed in f2ad1e9e8faa8dd382cd6b7bcddf210408a4238a.
See PR #74
