### ISSUE TITLE
Evaluator has attractive-nuisance do-it menu item on three-lines menu

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Sparkle#77]
There's a do it menu item on the evaluator pane.  Since I need a menu, and that's what I wanted to do rather than the badly-named accept, I used it and nothing happened.

It turns out there is a small message saying not yet implemented that pops up and goes away.  Unfortunately it's completely unnoticeable since it's covered by the giant Control-D. 

![image](https://user-images.githubusercontent.com/13142166/114931064-94d7a280-9dea-11eb-8989-84df2b65d7b6.png)

**Comment by martinmcclure** [comment]
The not-yet-implemented menu options have been removed.
