### ISSUE TITLE
Does debugger stack frame auto-select or not?

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Sparkle#78]
Given the method (see below, subbing ChangeFinder with class of your choice), the first halt shows a pane with the stack, but nothing is selected. However, if I continue, the second halt updates the stack and automatically selects the frame, popping another pane into my window. 

I don't know that I care if it's selected or not but it should be consistent.

After control-S:
![image](https://user-images.githubusercontent.com/13142166/114932353-3d3a3680-9dec-11eb-8c8a-0b6e5c23dca5.png)

Then after press the green continue arrow:
![image](https://user-images.githubusercontent.com/13142166/114932431-5b079b80-9dec-11eb-92c1-9789c17a89fa.png)

```classmethod ChangesFinder
testDebug
        "ChangesFinder testDebug"
|  keys  badKeys |
keys := { 'cat' . 'draw' . 'apple' }.
self halt.
badKeys := Array new.
badKeys addAll: (keys select: [:ea | ea trimSeparators size ~= ea size.  self halt. ]).
^badKeys printString
%
```

**Comment by rjsargent** [comment]
If you choose to automatically select a frame, I like what VAST does. It searches for the first frame for one of a number of "interesting" selectors and selects the sender if there is such a frame. It selects the top frame if it cannot find a better choice.
This has the benefit of showing the frame that actually had the problem.

e.g. #(#doesNotUnderstand: #halt #halt: #breakpointEncountered: #primitiveFailed #error:)
and for GBS: #(#pause #_doesNotUnderstand:args:envId:reason:)

**Comment by dalehenrich** [comment]
Interestingly enough single stepping through this method from the first halt gets stuck on `badKeys := Array new.` in topaz ... which is a bug that Eric and I have seen with sparkle (scaffolding) and topaz before ... but this is a reproducible test case and I've reported it to Allen (via slack) ... 

in topaz, using continue (I assume that is what the "green button" is) repeatedly doing a continue ends up with a seris UncontinuableErrors...

**Comment by martinmcclure** [comment]
The top frame pane is now opened when the debugger first opens.
