### ISSUE TITLE
Direct login server.sh depends on ROWAN_PROJECTS_HOME

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Sparkle#80]
Sparkle/src-gs/server.sh, which is how you are supposed to run a listening gem for a direct connection, requires ROWAN_PROJECTS_HOME...

Can't open the file: /Sparkle/src-gs/runServerLoop.topaz
errno=2,ENOENT, The file or directory specified cannot be found

**Comment by martinmcclure** [comment]
Removed remaining requirements for ROWAN_PROJECTS_HOME when using a non-Rowan stone.
