### ISSUE TITLE
would like scaffolding code to include api "step out" 

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Sparkle#89]
Jadeite has the concept of "stepping out"  of blocks.  Ultimately, it calls `GsProcess>>_stepOverInFrame:` which I *think* steps out of blocks - or tries to. (Currently, the skaffolding exposes `GsProcess>>stepOverFromLevel:` which behaves differently) 

It is worth a little investigation to see if exposing this as an additional api would make the sparkle debugger more useful.

**Comment by martinmcclure** [comment]
I spent a while looking through the stepping code in the 3.7.0 base. I can't see any differences in _stepOverInFrame: as compared to #stepOverFromLevel: that would step out of blocks. Both set the breakpoints using #_setBreaksForStepOverFromLevel:. 
I recommend taking a close look at what level argument Jadeite is passing to _stepOverInFrame:. If it's the level of the home method's frame, things are operating according to my understanding. If it's being successful in stepping out while passing the level of the block's frame, then my understanding needs more work.

**Comment by martinmcclure** [comment]
AFAIK, Dale's scaffolding is no longer being used except as a code reference, so closing this issue.
A "step out" feature sounds useful, but we'll need a precise definition of what it's supposed to do.
