### ISSUE TITLE
Inspecting large objects is slow

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/Sparkle#94]
Customer notes that "inspecting a dictionary of basicSize of avout 24000k slots, requires a sizeable amount of time."

A simple test case on a local machine, inspecting "Array new: 24000"  takes about 20 seconds. I don't know how much of this time is taken by RSR, will need to do some profiling with Kurt.

**Comment by kurtkilpela** [comment]
Removed O(n^2) algorithm in Sparkle UI. Inspecting a 24000 element dictionary resulted a list of >51000 elements. The example case now takes~6 seconds down from ~30. Much of the remaining time is used by evaluating the expression, creating snapshots of the structures, and pushing the data over the wire.

See 3c563c0c4d420ccf2c13df7f59d89f036f91f010
