### ISSUE TITLE
Not compatible with latest version of spec

### ISSUE THREAD

**Issue by sonibla** [GemTalk/Sparkle#98]
Hello

Sparkle installation crashes on most recent Pharo images because some Spec2 classes were renamed

SpLayoutDirectionVertical, SpLayoutDirectionHorizontal, SpStyleClass were renamed to SpVerticalLayoutDirection, SpHorizontalLayoutDirection, SpClassStyle

**Comment by martinmcclure** [comment]
Thanks for trying Sparkle (still very much a work in progress) and your contribution!
The branch "main" is essentially only for rolling releases. If you load from main, you should load from the Pharo build specified in the documentation.
If you want to use the latest Pharo 9 builds, or if you want to contribute to Sparkle, you should use the branch "development," which is the branch that the development team shares.
